name: Check PR Format

on:
  pull_request:
    branches:
      - master

jobs:
  check-format:
    name: Check PR Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout Repo
      - uses: actions/setup-node@v4
        name: Setup Node.js
        with:
          node-version: '20.x'
          check-latest: true
      - name: Install Yarn
        run: npm install -g yarn
      - name: Install dependencies
        run: yarn install
      - name: Run checker
        run: |
          yarn docs:format:check -a

  remark-lint:
    name: Check PR with remark-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout Repo
      - uses: actions/setup-node@v4
        name: Setup Node.js
        with:
          node-version: '20.x'
          check-latest: true
      - name: Install Yarn
        run: npm install -g yarn
      - name: Install dependencies
        run: yarn install
      - name: Run bot formatter
        run: |
          yarn docs:format:remark
      - name: Run ruff
        run: |
          ruff format ./docs
      - name: Check for changes
        run: |
          git diff --exit-code
